/* ============================================================
   Discount System Redesign - Phase 1 schema

   Goals:
   - Persist discount INTENT separately from any ALLOCATION.
   - Support multiple discounts per order and per item.
   - Preserve auditability for receipts/refunds/reporting.
   ============================================================ */

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'TBL_POS_DISCOUNT' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.TBL_POS_DISCOUNT
    (
        ID                 INT             IDENTITY(1,1) PRIMARY KEY,
        ORDER_ID           INT             NOT NULL,
        PRODUCT_ID         INT             NULL, -- set for ITEM scope; NULL for SUBTOTAL scope
        SCOPE              VARCHAR(20)     NOT NULL, -- ITEM | SUBTOTAL (future: ORDER_TOTAL, SHIPPING, etc.)
        VALUE_TYPE         VARCHAR(10)     NOT NULL, -- PERCENT | AMOUNT
        VALUE              DECIMAL(18,4)   NOT NULL CONSTRAINT DF_POS_DISCOUNT_VALUE DEFAULT (0),
        APPLIED_BASE_AMOUNT DECIMAL(18,2)  NOT NULL CONSTRAINT DF_POS_DISCOUNT_BASE DEFAULT (0), -- base at time of application
        APPLIED_AMOUNT     DECIMAL(18,2)   NOT NULL CONSTRAINT DF_POS_DISCOUNT_APPLIED DEFAULT (0), -- computed applied amount
        SOURCE             VARCHAR(30)     NOT NULL CONSTRAINT DF_POS_DISCOUNT_SOURCE DEFAULT ('Unknown'),
        REFERENCE          NVARCHAR(80)    NULL,
        DESCRIPTION        NVARCHAR(200)   NULL,
        PRIORITY           INT             NOT NULL CONSTRAINT DF_POS_DISCOUNT_PRIORITY DEFAULT (0),
        IS_STACKABLE       BIT             NOT NULL CONSTRAINT DF_POS_DISCOUNT_STACKABLE DEFAULT (1),
        CREATED_ON         DATETIME        NOT NULL CONSTRAINT DF_POS_DISCOUNT_CREATED DEFAULT (GETDATE()),
        CREATED_BY         NVARCHAR(80)    NULL,
        CONSTRAINT FK_POS_DISCOUNT_ORDER FOREIGN KEY (ORDER_ID) REFERENCES dbo.TBL_SP_PSO_ORDER(ID),
        CONSTRAINT CK_POS_DISCOUNT_SCOPE CHECK (SCOPE IN ('ITEM', 'SUBTOTAL')),
        CONSTRAINT CK_POS_DISCOUNT_VALUE_TYPE CHECK (VALUE_TYPE IN ('PERCENT', 'AMOUNT'))
    );

    CREATE INDEX IX_POS_DISCOUNT_ORDER ON dbo.TBL_POS_DISCOUNT (ORDER_ID, ID);
    CREATE INDEX IX_POS_DISCOUNT_ORDER_SCOPE ON dbo.TBL_POS_DISCOUNT (ORDER_ID, SCOPE);
    CREATE INDEX IX_POS_DISCOUNT_ORDER_PRODUCT ON dbo.TBL_POS_DISCOUNT (ORDER_ID, PRODUCT_ID);
END
ELSE
BEGIN
    PRINT 'TBL_POS_DISCOUNT already exists; skipping create.';
END;

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'TBL_POS_DISCOUNT_ALLOCATION' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.TBL_POS_DISCOUNT_ALLOCATION
    (
        ID               INT            IDENTITY(1,1) PRIMARY KEY,
        DISCOUNT_ID      INT            NOT NULL,
        ORDER_ID         INT            NOT NULL,
        PRODUCT_ID       INT            NOT NULL,
        BASIS_AMOUNT     DECIMAL(18,2)  NOT NULL CONSTRAINT DF_POS_ALLOC_BASIS DEFAULT (0),
        ALLOCATED_AMOUNT DECIMAL(18,2)  NOT NULL CONSTRAINT DF_POS_ALLOC_AMOUNT DEFAULT (0),
        CREATED_ON       DATETIME       NOT NULL CONSTRAINT DF_POS_ALLOC_CREATED DEFAULT (GETDATE()),
        CONSTRAINT FK_POS_ALLOC_DISCOUNT FOREIGN KEY (DISCOUNT_ID) REFERENCES dbo.TBL_POS_DISCOUNT(ID) ON DELETE CASCADE,
        CONSTRAINT FK_POS_ALLOC_ORDER FOREIGN KEY (ORDER_ID) REFERENCES dbo.TBL_SP_PSO_ORDER(ID),
        CONSTRAINT UQ_POS_ALLOC UNIQUE (DISCOUNT_ID, PRODUCT_ID)
    );

    CREATE INDEX IX_POS_ALLOC_ORDER ON dbo.TBL_POS_DISCOUNT_ALLOCATION (ORDER_ID);
    CREATE INDEX IX_POS_ALLOC_DISCOUNT ON dbo.TBL_POS_DISCOUNT_ALLOCATION (DISCOUNT_ID);
END
ELSE
BEGIN
    PRINT 'TBL_POS_DISCOUNT_ALLOCATION already exists; skipping create.';
END;

