/* ============================================================
   Held Sale (draft cart) discounts - Phase 1

   Holds discount intent for later checkout, without allocation.
   ============================================================ */

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'TBL_POS_HELD_SALE_DISCOUNT' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.TBL_POS_HELD_SALE_DISCOUNT
    (
        ID           INT            IDENTITY(1,1) PRIMARY KEY,
        HELD_SALE_ID INT            NOT NULL,
        PRODUCT_ID   INT            NULL,
        SCOPE        VARCHAR(20)    NOT NULL,  -- ITEM | SUBTOTAL
        VALUE_TYPE   VARCHAR(10)    NOT NULL,  -- PERCENT | AMOUNT
        VALUE        DECIMAL(18,4)  NOT NULL CONSTRAINT DF_POS_HLD_DISC_VALUE DEFAULT (0),
        SOURCE       VARCHAR(30)    NOT NULL CONSTRAINT DF_POS_HLD_DISC_SOURCE DEFAULT ('Unknown'),
        REFERENCE    NVARCHAR(80)   NULL,
        DESCRIPTION  NVARCHAR(200)  NULL,
        PRIORITY     INT            NOT NULL CONSTRAINT DF_POS_HLD_DISC_PRIORITY DEFAULT (0),
        IS_STACKABLE BIT            NOT NULL CONSTRAINT DF_POS_HLD_DISC_STACKABLE DEFAULT (1),
        CREATED_ON   DATETIME       NOT NULL CONSTRAINT DF_POS_HLD_DISC_CREATED DEFAULT (GETDATE()),
        CREATED_BY   NVARCHAR(80)   NULL,
        CONSTRAINT FK_POS_HLD_DISC_HEADER FOREIGN KEY (HELD_SALE_ID) REFERENCES dbo.TBL_POS_HELD_SALE(ID) ON DELETE CASCADE,
        CONSTRAINT CK_POS_HLD_DISC_SCOPE CHECK (SCOPE IN ('ITEM', 'SUBTOTAL')),
        CONSTRAINT CK_POS_HLD_DISC_VALUE_TYPE CHECK (VALUE_TYPE IN ('PERCENT', 'AMOUNT'))
    );

    CREATE INDEX IX_POS_HLD_DISC_HEADER ON dbo.TBL_POS_HELD_SALE_DISCOUNT (HELD_SALE_ID, ID);
    CREATE INDEX IX_POS_HLD_DISC_HEADER_SCOPE ON dbo.TBL_POS_HELD_SALE_DISCOUNT (HELD_SALE_ID, SCOPE);
END
ELSE
BEGIN
    PRINT 'TBL_POS_HELD_SALE_DISCOUNT already exists; skipping create.';
END;

