IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'TBL_POS_HELD_SALE' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.TBL_POS_HELD_SALE
    (
        ID               INT             IDENTITY(1,1) PRIMARY KEY,
        HOLD_REFERENCE   NVARCHAR(40)    NOT NULL,
        DEALER_ID        INT             NULL,
        DEALER_NAME      NVARCHAR(150)   NOT NULL,
        ITEMS_COUNT      INT             NOT NULL CONSTRAINT DF_POS_HELD_ITEMS DEFAULT (0),
        SUBTOTAL         DECIMAL(18,2)   NOT NULL CONSTRAINT DF_POS_HELD_SUBTOTAL DEFAULT (0),
        DISCOUNT_PERCENT DECIMAL(9,2)    NOT NULL CONSTRAINT DF_POS_HELD_DISC_PCT DEFAULT (0),
        DISCOUNT_AMOUNT  DECIMAL(18,2)   NOT NULL CONSTRAINT DF_POS_HELD_DISC_AMT DEFAULT (0),
        TAX_PERCENT      DECIMAL(9,2)    NOT NULL CONSTRAINT DF_POS_HELD_TAX_PCT DEFAULT (0),
        TAX_AMOUNT       DECIMAL(18,2)   NOT NULL CONSTRAINT DF_POS_HELD_TAX_AMT DEFAULT (0),
        TOTAL_AMOUNT     DECIMAL(18,2)   NOT NULL CONSTRAINT DF_POS_HELD_TOTAL DEFAULT (0),
        CREATED_ON       DATETIME        NOT NULL CONSTRAINT DF_POS_HELD_CREATED DEFAULT (GETDATE()),
        CREATED_BY       NVARCHAR(80)    NULL
    );

    CREATE UNIQUE INDEX IX_TBL_POS_HELD_SALE_REFERENCE ON dbo.TBL_POS_HELD_SALE (HOLD_REFERENCE);
    CREATE INDEX IX_TBL_POS_HELD_SALE_CREATED ON dbo.TBL_POS_HELD_SALE (CREATED_ON DESC);
END
ELSE
BEGIN
    PRINT 'TBL_POS_HELD_SALE already exists; skipping create.';
END;

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'TBL_POS_HELD_SALE_ITEM' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.TBL_POS_HELD_SALE_ITEM
    (
        ID            INT            IDENTITY(1,1) PRIMARY KEY,
        HELD_SALE_ID  INT            NOT NULL,
        PRODUCT_ID    INT            NOT NULL,
        SKU_CODE      NVARCHAR(80)   NULL,
        ITEM_NAME     NVARCHAR(200)  NOT NULL,
        UNIT_PRICE    DECIMAL(18,2)  NOT NULL,
        LIST_UNIT_PRICE DECIMAL(18,4) NULL,
        QUANTITY      INT            NOT NULL,
        TAX_RATE      DECIMAL(9,4)   NOT NULL CONSTRAINT DF_POS_HELD_ITEM_TAX DEFAULT (0),
        LINE_TOTAL    DECIMAL(18,2)  NOT NULL,
        THUMBNAIL_URL NVARCHAR(500)  NULL,
        CONSTRAINT FK_POS_HELD_ITEM_HEADER FOREIGN KEY (HELD_SALE_ID) REFERENCES dbo.TBL_POS_HELD_SALE(ID) ON DELETE CASCADE
    );

    CREATE INDEX IX_TBL_POS_HELD_ITEM_HEADER ON dbo.TBL_POS_HELD_SALE_ITEM (HELD_SALE_ID);
END
ELSE
BEGIN
    PRINT 'TBL_POS_HELD_SALE_ITEM already exists; skipping create.';
END;
