IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'TBL_SP_PSO_PAYMENT_2' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.TBL_SP_PSO_PAYMENT_2
    (
        ID                INT             IDENTITY(1,1) PRIMARY KEY,
        ORDER_ID          INT             NOT NULL,
        PAYMENT_REFERENCE VARCHAR(50)     NULL,
        PAYMENT_METHOD    VARCHAR(30)     NOT NULL,
        PAID_AMOUNT       DECIMAL(18,2)   NOT NULL,
        OUTSTANDING       DECIMAL(18,2)   NOT NULL CONSTRAINT DF_SP_PAYMENT_OUTSTANDING DEFAULT (0),
        CURRENCY_CODE     CHAR(3)         NOT NULL CONSTRAINT DF_SP_PAYMENT_CURRENCY DEFAULT ('AED'),
        IS_PARTIAL        BIT             NOT NULL CONSTRAINT DF_SP_PAYMENT_PARTIAL DEFAULT (0),
        CREATED_ON        DATETIME        NOT NULL CONSTRAINT DF_SP_PAYMENT_CREATED DEFAULT (GETDATE()),
        CREATED_BY        VARCHAR(50)     NULL,
        NOTES             NVARCHAR(500)   NULL,
        CONSTRAINT FK_SP_PAYMENT_ORDER FOREIGN KEY (ORDER_ID) REFERENCES dbo.TBL_SP_PSO_ORDER(ID)
    );

    CREATE INDEX IX_TBL_SP_PSO_PAYMENT_ORDER ON dbo.TBL_SP_PSO_PAYMENT_2 (ORDER_ID);
    CREATE INDEX IX_TBL_SP_PSO_PAYMENT_METHOD ON dbo.TBL_SP_PSO_PAYMENT_2 (PAYMENT_METHOD);
END
ELSE
BEGIN
    PRINT 'TBL_SP_PSO_PAYMENT_2 already exists; skipping create.';
END;

IF EXISTS (
    SELECT 1
    FROM sys.default_constraints
    WHERE name = 'DF_SP_PAYMENT_CURRENCY'
      AND parent_object_id = OBJECT_ID('dbo.TBL_SP_PSO_PAYMENT_2')
)
BEGIN
    ALTER TABLE dbo.TBL_SP_PSO_PAYMENT_2
    DROP CONSTRAINT DF_SP_PAYMENT_CURRENCY;
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.default_constraints
    WHERE name = 'DF_SP_PAYMENT_CURRENCY'
      AND parent_object_id = OBJECT_ID('dbo.TBL_SP_PSO_PAYMENT_2')
)
BEGIN
    ALTER TABLE dbo.TBL_SP_PSO_PAYMENT_2
    ADD CONSTRAINT DF_SP_PAYMENT_CURRENCY
    DEFAULT ('AED') FOR CURRENCY_CODE;
END;
