'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddCustomer

    Protected WithEvents litFormTitle As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents litFormSubtitle As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents lnkBackToCustomers As Global.System.Web.UI.WebControls.HyperLink

    Protected WithEvents pnlStatus As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents litStatus As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents pnlErrors As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents litErrors As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents hfDealerId As Global.System.Web.UI.WebControls.HiddenField

    Protected WithEvents hfReturnUrl As Global.System.Web.UI.WebControls.HiddenField

    Protected WithEvents txtDealerName As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtDealerCode As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtDealerOldCode As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtContactPerson As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtSalesPerson As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtSalesPersonId As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtTypeCode As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtParentId As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtBranch As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtBranchCode As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtDealerInvestment As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtDefaultDiscountPercentage As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtSalesTerritory As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents chkActive As Global.System.Web.UI.WebControls.CheckBox

    Protected WithEvents chkSmsAlerts As Global.System.Web.UI.WebControls.CheckBox

    Protected WithEvents chkAppLogin As Global.System.Web.UI.WebControls.CheckBox

    Protected WithEvents txtAddress As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtCity As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtState As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtCountry As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtWebsite As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtEmailCustomer As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtPhonePrimary As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtPhoneAlt1 As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtPhoneAlt2 As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtPhoneAlt3 As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtAltNumbers As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtContactNotes As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtEmailNotes As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtCnic As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtCnicExpiry As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtNtn As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtStn As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtLogin As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents fuTradeLicense As Global.System.Web.UI.WebControls.FileUpload

    Protected WithEvents litTradeLicenseStatus As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents fuCnic As Global.System.Web.UI.WebControls.FileUpload

    Protected WithEvents litCnicStatus As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents fuNtn As Global.System.Web.UI.WebControls.FileUpload

    Protected WithEvents litNtnStatus As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents fuLogo As Global.System.Web.UI.WebControls.FileUpload

    Protected WithEvents litLogoStatus As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents btnSaveCustomer As Global.System.Web.UI.WebControls.Button

    Protected WithEvents lnkCancel As Global.System.Web.UI.WebControls.HyperLink
End Class
