'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''litDate control.
    '''</summary>
    Protected WithEvents litDate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTime control.
    '''</summary>
    Protected WithEvents litTime As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblCashierName control.
    '''</summary>
    Protected WithEvents lblCashierName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''upPos control.
    '''</summary>
    Protected WithEvents upPos As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hfSelectedCategory control.
    '''</summary>
    Protected WithEvents hfSelectedCategory As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtSearch control.
    '''</summary>
    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearch control.
    '''</summary>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAllCategories control.
    '''</summary>
    Protected WithEvents btnAllCategories As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''rptCategories control.
    '''</summary>
    Protected WithEvents rptCategories As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblCatalogEmpty control.
    '''</summary>
    Protected WithEvents lblCatalogEmpty As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptProducts control.
    '''</summary>
    Protected WithEvents rptProducts As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''ddlCustomers control.
    '''</summary>
    Protected WithEvents ddlCustomers As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''litCartCount control.
    '''</summary>
    Protected WithEvents litCartCount As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btnClearCart control.
    '''</summary>
    Protected WithEvents btnClearCart As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''rptCart control.
    '''</summary>
    Protected WithEvents rptCart As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlEmptyCart control.
    '''</summary>
    Protected WithEvents pnlEmptyCart As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtDiscount control.
    '''</summary>
    Protected WithEvents txtDiscount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''litSubtotal control.
    '''</summary>
    Protected WithEvents litSubtotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTaxRate control.
    '''</summary>
    Protected WithEvents litTaxRate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTax control.
    '''</summary>
    Protected WithEvents litTax As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTotal control.
    '''</summary>
    Protected WithEvents litTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblCartMessage control.
    '''</summary>
    Protected WithEvents lblCartMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnHold control.
    '''</summary>
    Protected WithEvents btnHold As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNewSale control.
    '''</summary>
    Protected WithEvents btnNewSale As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCheckout control.
    '''</summary>
    Protected WithEvents btnCheckout As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''litModalTotal control.
    '''</summary>
    Protected WithEvents litModalTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''rblPaymentMethod control.
    '''</summary>
    Protected WithEvents rblPaymentMethod As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtPartialAmount control.
    '''</summary>
    Protected WithEvents txtPartialAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCheckoutError control.
    '''</summary>
    Protected WithEvents lblCheckoutError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnCancelPayment control.
    '''</summary>
    Protected WithEvents btnCancelPayment As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCompletePayment control.
    '''</summary>
    Protected WithEvents btnCompletePayment As Global.System.Web.UI.WebControls.Button
End Class
