'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''litDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litDate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTime As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblCashierName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCashierName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLogout As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''upPos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upPos As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hfSelectedCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSelectedCategory As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lnkManageProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkManageProducts As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''btnAllCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAllCategories As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''rptCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCategories As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblCatalogEmpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCatalogEmpty As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptProducts As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''ddlCustomers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCustomers As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnViewCustomerProfile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnViewCustomerProfile As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''litCartCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCartCount As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btnClearCart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClearCart As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''rptCart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCart As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlEmptyCart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEmptyCart As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtDiscount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiscount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlDiscountMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDiscountMode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''litSubtotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSubtotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTaxRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTaxRate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTax As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblCartMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCartMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnHold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHold As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnHeldBills control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHeldBills As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNewSale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNewSale As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCheckout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCheckout As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''litAmountDueHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAmountDueHeader As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litModalSubtotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litModalSubtotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litModalDiscount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litModalDiscount As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litModalTax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litModalTax As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litModalTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litModalTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txtModalTaxPercent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModalTaxPercent As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rblPaymentMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblPaymentMethod As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''pnlCorporatePayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCorporatePayment As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rblCorporatePaymentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblCorporatePaymentType As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtCorporatePartialAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCorporatePartialAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''litCashAmountDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCashAmountDue As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litCashChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCashChange As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txtCashReceived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCashReceived As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''litCardAmountDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCardAmountDue As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txtCardRrn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCardRrn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCardAuthCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCardAuthCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlCardStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCardStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCheckoutError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCheckoutError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnCancelPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelPayment As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCompletePayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCompletePayment As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''litHoldSummaryItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litHoldSummaryItems As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litHoldSummaryTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litHoldSummaryTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btnConfirmHold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmHold As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlHeldBillsEmpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHeldBillsEmpty As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rptHeldBills control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptHeldBills As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''hfAmountDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfAmountDue As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfBaseAmountDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfBaseAmountDue As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfCurrencySymbol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCurrencySymbol As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfIsCorporateCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIsCorporateCustomer As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfTaxableAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTaxableAmount As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfDefaultTaxPercent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDefaultTaxPercent As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfActiveHeldSaleId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfActiveHeldSaleId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfReceiptDownloadUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfReceiptDownloadUrl As Global.System.Web.UI.WebControls.HiddenField
End Class
