'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageProducts

    '''<summary>
    '''lnkBackToPos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBackToPos As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''pnlStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStatus As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litStatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''pnlErrors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlErrors As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litErrors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litErrors As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txtSparePartCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSparePartCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDisplayName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDisplayName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCategory As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBrand As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProductDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAddSkuRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddSkuRow As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rptSkus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSkus As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''btnSaveProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveProduct As Global.System.Web.UI.WebControls.Button
End Class
